import {$,el,field,option,panel,table,setStatus} from './common/dom.js';import {loadJSON} from './common/data.js';import {parseCSV} from './common/csv.js';import {downloadJSON,download} from './common/download.js';import {normalizeRecords,summarize} from './core.js';
const app=$('#app');let records=[],summary,source,catalog;
async function main(){catalog=await loadJSON('./data/catalog.json');const datasets=catalog.items.filter(i=>i.kind==='dataset'),plans=catalog.items.filter(i=>i.kind==='plan');const dataset=el('select',{id:'dataset'},datasets.map(d=>option(d.id,d.title)));const plan=el('select',{id:'analysis-plan'},plans.map(p=>option(p.id,p.title)));const upload=el('input',{id:'csv-upload',type:'file',accept:'.csv,text/csv'});
 const run=el('button',{id:'run-analysis',text:'Analyse synthetic dataset',onclick:change});dataset.addEventListener('change',change);plan.addEventListener('change',async()=>{const item=plans.find(p=>p.id===plan.value),p=await loadJSON('./'+item.path);$('#plan-detail').textContent=JSON.stringify(p,null,2);setStatus('Illustrative plan displayed; no real-study preregistration is implied.');});
 upload.addEventListener('change',async()=>{try{const file=upload.files[0];if(!file||file.size>2*1024*1024)throw new Error('Choose a CSV smaller than 2 MB');records=normalizeRecords(parseCSV(await file.text()));source='local synthetic CSV';summary=summarize(records);render();setStatus('Local synthetic file analysed.');}catch(e){setStatus(e.message,'error');}});
 app.append(el('div',{class:'layout'},[el('aside',{},[panel('Experiment controls',[field('Synthetic scenario',dataset),run,field('Local synthetic CSV',upload),field('Illustrative analysis plan',plan),el('pre',{id:'plan-detail'}),el('p',{class:'notice',text:'No patient data is included. Outcomes are invented demo counts, not clinical scores.'})])]),el('div',{id:'content'})]));await change();const p=await loadJSON('./'+plans[0].path);$('#plan-detail').textContent=JSON.stringify(p,null,2);
 async function change(){try{const item=datasets.find(d=>d.id===dataset.value);const response=await fetch('./'+item.path);if(!response.ok)throw new Error('Cannot load CSV');records=normalizeRecords(parseCSV(await response.text()));source=item.title;summary=summarize(records);render();setStatus('Synthetic example analysed; these are not research findings.');}catch(e){setStatus(e.message,'error');}}
}
function render(){const content=$('#content');content.replaceChildren();const format=value=>value===null?'not available':typeof value==='number'?value.toFixed(3):String(value);const stats=el('div',{class:'stats'},[['Complete pairs',summary.complete_pairs],['Missing rows',summary.missing_rows],['Paired difference',format(summary.mean_paired_difference)]].map(([label,value])=>el('div',{class:'stat'},[el('strong',{text:value}),el('span',{text:label})])));
 const interval=summary.interval?`${format(summary.interval.lower)} to ${format(summary.interval.upper)}`:'not available';content.append(panel('Synthetic analysis summary',[el('p',{class:'tag',text:source}),stats,el('p',{class:'muted',text:'Adapted minus original. 95% percentile bootstrap interval: '+interval+'. Resampling unit: complete participant pair.'}),el('div',{class:'actions'},[el('button',{id:'export-results',text:'Export result JSON',onclick:()=>downloadJSON({id:'SYN-ANALYSIS-001',project_id:'dementia-assessment-research',is_synthetic:true,created_at:new Date().toISOString(),payload:{source,summary}},'synthetic-analysis.json')}),el('button',{id:'export-report',class:'secondary',text:'Export text report',onclick:()=>download('Synthetic demonstration only\n'+source+'\n'+JSON.stringify(summary,null,2),'synthetic-report.txt')})])]),panel('Available-observation means',[table(['Original mean','Adapted mean','Rows','Participants'],[[format(summary.original_mean),format(summary.adapted_mean),summary.rows,summary.participants]])]),panel('Example records — first 12 rows',[el('div',{class:'scroll'},[table(['Fictional participant','Language','Condition','Demo count'],records.slice(0,12).map(r=>[r.participant_id,r.language,r.condition,r.demo_error_count]))])]));
}
main().catch(e=>setStatus(e.message,'error'));
